domain: danielverdugo.com
url: https://danielverdugo.com

encoding: "utf-8"

compress_html:
  clippings: all
  comments: all

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      lang: "en"

feed:
  path: /rss/index.xml

plugins:
  - jekyll-feed
  - jekyll-sitemap