domain: danielverdugo.com
url: https://danielverdugo.com

encoding: "utf-8"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  style: :compressed
  sass_dir: _includes

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      permalink: /:path/:basename/
      lang: "en"

feed:
  path: /rss/

safe: false